### PR TITLE
Updated design

### PR DESCRIPTION
**Pull request by ranbena**
According to https://discuss.redash.io/t/redash-preview-login-page/3833

Also has:
1. Mobile version
2. "Submitting" indications

Screen Shot 2019-05-22 at 18 39 21

### CODE REVIEW

**Comment by ranbena** [comment]
@arik All the html + js + css + assets are located in the same one file - easier for me to work on it like that. Lmk if you think these should be separate files.

This is a draft since the "Backend current version: 7.01 build abc123" part is hardcoded.
Is it even possible to retrieve this info at runtime? If not, I'll remove this line altogether.

**Comment by ranbena** [comment]
@arikfr any update regarding the server build info?
We can land this without this section.

**Comment by arikfr** [comment]
@ranbena aside from the backend version is this good to go?

**Comment by ranbena** [comment]
Yep

**Pull request merged**
